# Generated by Django 2.0.5 on 2018-05-09 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_update', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectCode', models.IntegerField()),
                ('subjectName', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.IntegerField()),
                ('eisu', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.IntegerField()),
                ('professor', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('lectureRoom', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hukbun', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studentgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eisu', models.CharField(blank=True, max_length=50, null=True)),
                ('certification', models.CharField(blank=True, max_length=50, null=True)),
                ('yearNsemester', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_design', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('valid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentHopeCareers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('ranking', models.IntegerField()),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('Enterprise', models.CharField(blank=True, max_length=50, null=True)),
                ('Salary', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hukbun', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('jumin', models.CharField(max_length=30, unique=True)),
                ('name_Hanja', models.CharField(blank=True, max_length=30, null=True)),
                ('name_English', models.CharField(blank=True, max_length=30, null=True)),
                ('campus', models.CharField(blank=True, max_length=30, null=True)),
                ('dayNight', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('variance', models.CharField(blank=True, max_length=30, null=True)),
                ('graduationCredit', models.IntegerField()),
                ('major', models.CharField(blank=True, max_length=30, null=True)),
                ('advisor', models.CharField(blank=True, max_length=30, null=True)),
                ('currentGrade', models.CharField(blank=True, max_length=30, null=True)),
                ('compleSemester', models.CharField(blank=True, max_length=30, null=True)),
                ('earlyGraduation', models.CharField(blank=True, max_length=30, null=True)),
                ('admission', models.DateField(blank=True, null=True)),
                ('enginCertification', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('cellPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('parentsPhone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studenthopecareers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_core.StudentInfo'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_core.StudentInfo'),
        ),
        migrations.AddField(
            model_name='latestupdate',
            name='StudentInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_core.StudentInfo'),
        ),
    ]
