# Generated by Django 2.0.5 on 2018-05-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='graduationCredit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
