# Generated by Django 2.0.5 on 2018-05-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_core', '0002_auto_20180509_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='admission',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
