# Generated by Django 2.0.5 on 2018-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_core', '0003_auto_20180509_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='jumin',
            field=models.CharField(max_length=30),
        ),
    ]
