# Generated by Django 2.0.5 on 2018-05-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_core', '0004_auto_20180509_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgrade',
            old_name='student',
            new_name='hukbun',
        ),
    ]
